[package]
name = "goodboy"
version = "0.1.0"
authors = ["aydar.media <me@aydar.media>"]
edition = "2021"

[dependencies]
clap = "2.33.1"
directories = "3.0.1"
toml = "0.5.11"
serde_derive = "1.0.158"
serde = "1.0.97"
rustyline = "7.0.0"
rpassword = "5.0.1"
sqlite = "0.30.4"